name = "ScottyStacks"
description = "Responsible for maintenance of ScottyLabs Full Stack Template"
website = "https://stacks.scottylabs.org"
server = "https://api.stacks.scottylabs.org"

[[repos]]
name = "ScottyStack"
description = "ScottyLabs Full Stack Template"

[[membership]]
timeframe = "2026-2027"
leads = ["Yuxiang-Huang"]

[[membership.members]]
github-username = "Yuxiang-Huang"
